#ifndef _USART_COMMANDS_H
#define _USART_COMMANDS_H

/* Support commands for AVR1 and AVR2. */

#define USART_CMD_LIGHT1_ON	0
#define USART_CMD_LIGHT1_OFF	1
#define USART_CMD_FAN_ON	2
#define USART_CMD_FAN_OFF	3
#define USART_CMD_FAN_DIR_L	4
#define USART_CMD_FAN_DIR_R	5
#define USART_CMD_MODE_AUTO	6
#define USART_CMD_MODE_MANU	7
#define USART_CMD_LIVING_OFF	8
#define USART_CMD_LIVING_ON	9
#define USART_CMD_BED_OFF	10
#define USART_CMD_BED_ON	11

#endif
